name: PR test
on:
  [push, pull_request]
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      
    - name: List
      shell: bash
      run: |
          `ls ${{ github.workspace }} > filelist`
          echo $filelist
          cat filelist | while read line ;
          do
            echo $line
          done
