name: PR test
on:
  [push, pull_request]
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps: 
    
    - uses: actions/checkout@v2
    - name: List  
      run: |
          filelist=`ls ${{ github.workspace }}`
          echo $filelist | while read line ;
          do
            fileline=`cat $line | sed '/^$/d' | wc -l`
            fileline=`echo "${fileline:(-1)}"`
            sum=$(($fileline%2))
            if [ $sum = 0 ]
                  then
                      echo "success"
                  else
                      exit(1)
            fi
          done
